site_name: Hoshikage
nav:
    - 入口: index.md
    - ゲームマスターの役割: GMsRole.md
    - キャラクター達の独白: CharactersMonologue.md
    - 真相: Truth.md
    - 謎解きのヒント＆回答: AnswersHints.md
    - 時系列まとめ: TimeCourses.md
    - ゲームの準備: GettingReady.md
    - ゲームの進行: Moderator.md
    - 追加情報の管理: AdditionalInfos.md
    - エンディングのイベント: EndingEvents.md
    - 君ならわかる！　『星陰』のルール説明: RulesBasic.md
    - ルールの補足: RulesAdditional.md
    - 素材置き場: Resources.md
    - あとがき: FromAuthor.md
theme:
  name: readthedocs
  language: 'ja'
extra:
  search:
    language: 'jp'

extra_css:
    - css/extra.css